version: "3.8"

services:
  web:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production

  playwright:
    image: web
    depends_on:
      - web
    entrypoint: ["npx", "playwright", "test"]
    environment:
      - CI=true
      - BASE_URL=http://web:3000
