version: "3.8"

services:
  web:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production

  playwright:
    image: mcr.microsoft.com/playwright:focal
    depends_on:
      - web
    volumes:
      - .:/app
    working_dir: /app
    command: npm run test:playwright
    environment:
      - CI=true
      - BASE_URL=http://web:3000
