name: Playwright Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose
        run: docker-compose -f docker-compose.playwright.yml up --abort-on-container-exit --exit-code-from playwright

      - name: Shutdown Docker Compose
        if: always()
        run: docker-compose -f docker-compose.playwright.yml down
